markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title
rdiscount:
  extensions: [smart]

name: Florian Rathgeber
title: Florian Rathgeber's site
url: http://kynan.github.io
domain: kynan.github.io
description: Computational scientist at [ECMWF](http://ecmwf.int) in Reading, UK. Pythonista. Cyclist. Open source / open data enthusiast. Hobbyist photographer. [PyData London](http://london.pydata.org) co-organiser. [Taarifa](http://taarifa.org) co-Founder.
twitter: frathgeber
github: kynan
googleplus: +FlorianRathgeber
gravatar_url: https://gravatar.com/avatar/d178a6201be696c466c41c355c671707
analytics_id: UA-42283836-1
disqus_shortname: frathgeber
