markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title
rdiscount:
  extensions: [smart]

name: Florian Rathgeber
url: http://kynan.github.io
domain: kynan.github.io
description: Computational scientist at ECMWF, Reading, UK. Pythonista. Open source / open data enthusiast, developer, contributor. Hobbyist photographer.
twitter: frathgeber
github: kynan
googleplus: +FlorianRathgeber
gravatar_url: http://gravatar.com/avatar/d178a6201be696c466c41c355c671707
analytics_id: UA-42283836-1
