markdown: redcarpet
pygments: true
permalink: /posts/:year-:month-:day-:title
rdiscount:
  extensions: [smart]

name: Florian Rathgeber
url: http://florianrathgeber.me
description: Computational scientist at Imperial College, London. Pythonista. Open source / open data enthusiast, developer, contributor. Hobbyist photographer.
twitter: frathgeber
github: kynan
gravatar_url: http://gravatar.com/avatar/d178a6201be696c466c41c355c671707
