# Permalinks
permalink:           blog/:year/:month/:day/:title

# Setup
title:               Not sorry for the inconvenience
tagline:
description:         "[Site Reliability Engineer](https://landing.google.com/sre) at Google in London, UK. Former Computational Scientist at [ECMWF](http://ecmwf.int) in Reading, UK. PhD from [Imperial College](https://imperial.ac.uk). Pulic speaker. Feminist. Pythonista. Cyclist. Open source / open data enthusiast. Hobbyist photographer. [PyData London](https://london.pydata.org) co-founder."
url:                 https://kynan.github.io
domain:              kynan.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Florian Rathgeber
  url:               https://twitter.com/frathgeber
  email:             florian.rathgeber@gmail.com

# Social
twitter: frathgeber
github: kynan
googleplus: +FlorianRathgeber
linkedin: florianrathgeber
flickr: frathgeber
gravatar_url: https://gravatar.com/avatar/d178a6201be696c466c41c355c671707
disqus_shortname: frathgeber

# Analytics
analytics_id: UA-42283836-1
